# Generated by Django 5.2.1 on 2025-05-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='sector',
            new_name='industry',
        ),
    ]
