# Generated by Django 5.2.1 on 2025-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sector_companyprofile_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='extraction_success',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='use_for_analysis',
            field=models.BooleanField(default=True),
        ),
    ]
