# Generated by Django 5.2.1 on 2025-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pdffile_origin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
