# Generated by Django 5.2.1 on 2025-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyurl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
