# Generated by Django 5.2.1 on 2025-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_is_active_companyurl_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
