# Generated by Django 5.2.1 on 2025-06-10 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_companyprofile_last_scraped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='origin_url',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='PDFScrapeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_dates', to='api.pdffile')),
            ],
        ),
        migrations.CreateModel(
            name='PDFOriginURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_urls', to='api.pdffile')),
            ],
            options={
                'unique_together': {('pdf_file', 'url')},
            },
        ),
    ]
