# Generated by Django 5.2.1 on 2025-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_pdffile_origin_url_remove_pdffile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
