# Generated by Django 4.2.23 on 2025-06-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pdffile_file_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedPDFCandidate',
        ),
    ]
