# Generated by Django 4.2.23 on 2025-06-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_scrapedpdfcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('pdf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='api.pdffile')),
            ],
        ),
    ]
